"use client";

import { useState, useEffect } from "react";
import { Notebook, X } from "@phosphor-icons/react";
import { motion, AnimatePresence } from "motion/react";
import { SectionHeader } from "@/components/primitives/SectionHeader";
import { postFullAudit } from "@/lib/api";
import type { DemoResult, ValidationResult } from "@/lib/types";

interface Props {
  summary: string;
  results?: ValidationResult[];
  demoResult?: DemoResult;
}

function buildBullets(results: ValidationResult[]) {
  const passed = results.filter((r) => r.status === "passed").length;
  const negotiable = results.filter((r) => r.status === "negotiable").length;
  const rejected = results.filter((r) => r.status === "rejected").length;
  const missing = results.filter((r) => r.status === "missing_information").length;

  const bullets: { color: string; label: string }[] = [];
  if (passed > 0)
    bullets.push({ color: "bg-success", label: `${passed} seller${passed !== 1 ? "s" : ""} passed validation` });
  if (negotiable > 0)
    bullets.push({ color: "bg-warning", label: `${negotiable} seller${negotiable !== 1 ? "s" : ""} negotiable` });
  if (rejected > 0) {
    const failedConstraints = results
      .filter((r) => r.status === "rejected")
      .flatMap((r) => r.failed_constraints).length;
    bullets.push({ color: "bg-danger", label: `${rejected} offer${rejected !== 1 ? "s" : ""} rejected (${failedConstraints} constraint${failedConstraints !== 1 ? "s" : ""})` });
  }
  if (missing > 0)
    bullets.push({ color: "bg-text-3", label: `${missing} with missing information` });
  return bullets;
}

export function AuditSummary({ summary, results, demoResult }: Props) {
  const [fullText, setFullText] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [showFull, setShowFull] = useState(false);

  const bullets = results ? buildBullets(results) : null;
  const displayText = showFull && fullText ? fullText : summary;

  useEffect(() => {
    if (!demoResult || loading || fullText) return;
    setLoading(true);
    postFullAudit(demoResult)
      .then((narrative) => setFullText(narrative))
      .catch(() => {})
      .finally(() => setLoading(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm">
      <SectionHeader
        letter="I"
        title="Audit Summary"
        subtitle="generated by Audit/Summary Subagent"
        right={
          showFull ? (
            <button
              onClick={() => setShowFull(false)}
              className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface-2 px-2.5 py-1 text-[11px] text-text-2 transition-colors hover:border-red-200 hover:bg-danger-soft hover:text-danger"
            >
              <X className="h-3.5 w-3.5" />
              Close
            </button>
          ) : (
            <button
              onClick={() => { if (fullText) setShowFull(true); }}
              disabled={!fullText}
              className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface-2 px-2.5 py-1 text-[11px] text-text-2 transition-colors hover:border-accent-border hover:bg-accent-soft hover:text-accent disabled:cursor-wait disabled:opacity-60"
            >
              <Notebook className="h-3.5 w-3.5" />
              {loading ? "Generating…" : "Full narrative"}
            </button>
          )
        }
      />

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-12">
        <div className={bullets && bullets.length > 0 ? "lg:col-span-8" : "lg:col-span-12"}>
          <AnimatePresence mode="wait">
            <motion.div
              key="audit-text"
              initial={{ opacity: 0, y: 4 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.25, ease: [0.23, 1, 0.32, 1] }}
            >
              <div className="space-y-3">
                {displayText.split(/\n\n+/).map((para, i) => (
                  <p key={i} className="max-w-[68ch] text-[13.5px] leading-relaxed text-text-1">
                    {para}
                  </p>
                ))}
                {loading && (
                  <p className="text-[13.5px] leading-relaxed text-text-3 animate-pulse">…</p>
                )}
              </div>
            </motion.div>
          </AnimatePresence>
        </div>

        {bullets && bullets.length > 0 && (
          <div className="lg:col-span-4">
            <ul className="flex flex-col gap-2 rounded-xl border border-border bg-surface-2/50 px-4 py-3 text-[12px] text-text-2">
              {bullets.map((b) => (
                <Bullet key={b.label} color={b.color}>
                  {b.label}
                </Bullet>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}

function Bullet({
  color,
  children,
}: {
  color: string;
  children: React.ReactNode;
}) {
  return (
    <li className="flex items-center gap-2">
      <span className={`h-1.5 w-1.5 shrink-0 rounded-full ${color}`} />
      <span>{children}</span>
    </li>
  );
}
