"use client";

import { Notebook } from "@phosphor-icons/react";
import { SectionHeader } from "@/components/primitives/SectionHeader";

interface Props {
  summary: string;
}

export function AuditSummary({ summary }: Props) {
  return (
    <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm">
      <SectionHeader
        letter="I"
        title="Audit Summary"
        subtitle="generated by Audit/Summary Subagent"
        right={
          <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface-2 px-2.5 py-1 text-[11px] text-text-2">
            <Notebook className="h-3.5 w-3.5" />
            full narrative
          </span>
        }
      />
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-12">
        <div className="lg:col-span-8">
          <p className="max-w-[68ch] text-[13.5px] leading-relaxed text-text-1">
            {summary}
          </p>
        </div>
        <div className="lg:col-span-4">
          <ul className="flex flex-col gap-2 rounded-xl border border-border bg-surface-2/50 px-4 py-3 text-[12px] text-text-2">
            <Bullet color="bg-success">2 sellers passed validation</Bullet>
            <Bullet color="bg-warning">1 seller negotiable (warranty)</Bullet>
            <Bullet color="bg-danger">1 offer rejected (3 constraints)</Bullet>
            <Bullet color="bg-text-3">2 sellers had no compliant offer</Bullet>
          </ul>
        </div>
      </div>
    </div>
  );
}

function Bullet({
  color,
  children,
}: {
  color: string;
  children: React.ReactNode;
}) {
  return (
    <li className="flex items-center gap-2">
      <span className={`h-1.5 w-1.5 shrink-0 rounded-full ${color}`} />
      <span>{children}</span>
    </li>
  );
}
