"use client";

import { Notebook } from "@phosphor-icons/react";
import { SectionHeader } from "@/components/primitives/SectionHeader";
import type { ValidationResult } from "@/lib/types";

interface Props {
  summary: string;
  results?: ValidationResult[];
}

function buildBullets(results: ValidationResult[]) {
  const passed = results.filter((r) => r.status === "passed").length;
  const negotiable = results.filter((r) => r.status === "negotiable").length;
  const rejected = results.filter((r) => r.status === "rejected").length;
  const missing = results.filter((r) => r.status === "missing_information").length;

  const bullets: { color: string; label: string }[] = [];
  if (passed > 0)
    bullets.push({ color: "bg-success", label: `${passed} seller${passed !== 1 ? "s" : ""} passed validation` });
  if (negotiable > 0)
    bullets.push({ color: "bg-warning", label: `${negotiable} seller${negotiable !== 1 ? "s" : ""} negotiable` });
  if (rejected > 0) {
    const failedConstraints = results
      .filter((r) => r.status === "rejected")
      .flatMap((r) => r.failed_constraints).length;
    bullets.push({ color: "bg-danger", label: `${rejected} offer${rejected !== 1 ? "s" : ""} rejected (${failedConstraints} constraint${failedConstraints !== 1 ? "s" : ""})` });
  }
  if (missing > 0)
    bullets.push({ color: "bg-text-3", label: `${missing} with missing information` });
  return bullets;
}

export function AuditSummary({ summary, results }: Props) {
  const bullets = results ? buildBullets(results) : null;

  return (
    <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm">
      <SectionHeader
        letter="I"
        title="Audit Summary"
        subtitle="generated by Audit/Summary Subagent"
        right={
          <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface-2 px-2.5 py-1 text-[11px] text-text-2">
            <Notebook className="h-3.5 w-3.5" />
            full narrative
          </span>
        }
      />
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-12">
        <div className={bullets && bullets.length > 0 ? "lg:col-span-8" : "lg:col-span-12"}>
          <p className="max-w-[68ch] text-[13.5px] leading-relaxed text-text-1">
            {summary}
          </p>
        </div>
        {bullets && bullets.length > 0 && (
          <div className="lg:col-span-4">
            <ul className="flex flex-col gap-2 rounded-xl border border-border bg-surface-2/50 px-4 py-3 text-[12px] text-text-2">
              {bullets.map((b) => (
                <Bullet key={b.label} color={b.color}>
                  {b.label}
                </Bullet>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}

function Bullet({
  color,
  children,
}: {
  color: string;
  children: React.ReactNode;
}) {
  return (
    <li className="flex items-center gap-2">
      <span className={`h-1.5 w-1.5 shrink-0 rounded-full ${color}`} />
      <span>{children}</span>
    </li>
  );
}
